# Generated by Django 5.2.4 on 2025-07-30 09:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='记录日期')),
                ('bedtime', models.TimeField(verbose_name='入睡时间')),
                ('wakeup_time', models.TimeField(verbose_name='起床时间')),
                ('quality', models.PositiveIntegerField(help_text='1-5分，5分为最佳', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='睡眠质量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '睡眠记录',
                'verbose_name_plural': '睡眠记录',
                'ordering': ['-date'],
            },
        ),
    ]
