# Generated by Django 5.2.4 on 2025-07-30 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeprecord',
            name='quality',
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='记录日期'),
        ),
    ]
