# Generated by Django 5.2.4 on 2025-08-08 12:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sleeprecord_quality_alter_sleeprecord_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='饮食日期')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '零食')], max_length=20, verbose_name='餐别')),
                ('food_name', models.CharField(max_length=100, verbose_name='食物名称')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='份量(g/ml)')),
                ('calories', models.PositiveIntegerField(verbose_name='卡路里')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '饮食记录',
                'verbose_name_plural': '饮食记录',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='运动日期')),
                ('exercise_type', models.CharField(choices=[('running', '跑步'), ('walking', '步行'), ('cycling', '骑行'), ('swimming', '游泳'), ('gym', '健身房'), ('other', '其他')], max_length=20, verbose_name='运动类型')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='运动时长(分钟)')),
                ('calories', models.PositiveIntegerField(verbose_name='消耗卡路里')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '运动记录',
                'verbose_name_plural': '运动记录',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='年龄')),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='U', max_length=1, verbose_name='性别')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='身高(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='体重(kg)')),
                ('daily_sleep_goal', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)], verbose_name='每日睡眠目标(小时)')),
                ('daily_exercise_goal', models.PositiveSmallIntegerField(default=500, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(2000)], verbose_name='每日运动目标(卡路里)')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A型'), ('B', 'B型'), ('AB', 'AB型'), ('O', 'O型')], max_length=10, verbose_name='血型')),
                ('allergies', models.TextField(blank=True, verbose_name='过敏史')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户健康档案',
                'verbose_name_plural': '用户健康档案',
            },
        ),
    ]
