# Generated by Django 5.2.4 on 2025-08-08 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dietrecord_exerciserecord_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sleep', '睡眠不足'), ('exercise', '运动不足')], max_length=20, verbose_name='提醒类型')),
                ('message', models.CharField(max_length=200, verbose_name='提醒消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('consecutive_days', models.PositiveSmallIntegerField(default=0, verbose_name='连续天数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '健康提醒',
                'verbose_name_plural': '健康提醒',
                'ordering': ['-created_at'],
            },
        ),
    ]
